require_relative 'sub_systems/base'
require_relative 'sub_systems/call_log'
require_relative 'sub_systems/clipboard'
require_relative 'sub_systems/location'
require_relative 'sub_systems/sms'
require_relative 'sub_systems/tts'
require_relative 'sub_systems/sensor'
